### ISSUE TITLE
Do not use while (true)

### ISSUE THREAD

**Issue by bokherus** [OOP2018/guessing-game-WuttipatNilsiri#2]
You can use boolean value returned from `game.guess(number)` to determine when your loop should stop.

https://github.com/OOP2018/guessing-game-WuttipatNilsiri/blob/d63ec0cd32d1c5ff994e36e8d6800efa0efe5982/src/GameSolver.java#L24-L43

**Comment by WuttipatNilsiri** [comment]
i just try as you said
